### ISSUE TITLE
`f:asset.script identifier` Parameter should be "required: true"

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/fluid-documentation-generator#9]
The parameter `identifier` of `f:asset.script` is a required parameter as per PHP `->registerArgument()`:

https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/ViewHelpers/Asset/ScriptViewHelper.php#L88-L92

In the rendered docs

https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Asset/Script.html#asset-script-identifier

it is shown as "required: false", though.

**Comment by linawolf** [comment]
This is a general issue with the Fluid ViewHelper Documentation Generation and will be solved by https://github.com/TYPO3-Documentation/fluid-documentation-generator/issues/10
